name = "hammal"
account_id = "5fc5815bb135fac8a5ee4e0891309940"
main = "src/index.ts"
workers_dev = true
compatibility_date = "2024-06-08"

kv_namespaces = [
	 { binding = "HAMMAL_CACHE", id = "8a118abeba71427aa5b76f1b53a2e044" }
]
